import type { Metadata } from "next";
import "./globals.css";
import { Prompt, Montserrat } from 'next/font/google';
import Header from "@/Components/Header";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const prompt = Prompt({
  subsets: ['latin'],

  weight: ['400','700', '800', '900'],
  variable: '--font-prompt',
  display: 'swap',
  preload: true,
});

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
  variable: '--font-montserrat',
  display: 'swap',
  preload: true,
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${prompt.variable} ${montserrat.variable}`}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
